analyzer:
  exclude:
    - "**/*.mocks.dart"
  errors:
    unused_import: ignore
    unused_local_variable: ignore

linter:
  rules:
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes