// Mocks for auth_provider_test.dart
// This file is typically generated by build_runner but we're creating it manually

import 'package:mockito/mockito.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class MockFirebaseAuth extends Mock implements FirebaseAuth {
  @override
  Stream<User?> authStateChanges() => const Stream.empty();
}

class MockFirebaseFirestore extends Mock implements FirebaseFirestore {
  @override
  CollectionReference<Map<String, dynamic>> collection(String collectionPath) {
    return MockCollectionReference();
  }
}

class MockCollectionReference extends Mock implements CollectionReference<Map<String, dynamic>> {
  @override
  DocumentReference<Map<String, dynamic>> doc(String documentPath) {
    return MockDocumentReference();
  }
}

class MockDocumentReference extends Mock implements DocumentReference<Map<String, dynamic>> {
  @override
  Future<DocumentSnapshot<Map<String, dynamic>>> get([GetOptions? options]) async {
    return MockDocumentSnapshot();
  }
}

class MockDocumentSnapshot extends Mock implements DocumentSnapshot<Map<String, dynamic>> {
  @override
  bool get exists => false;
  
  @override
  Map<String, dynamic>? data() => null;
}

class MockUser extends Mock implements User {}
class MockUserCredential extends Mock implements UserCredential {}

// Export the classes to match what the annotations would generate
export 'auth_provider_test.dart';