// Mocks for auth_provider_test.dart
// This file is typically generated by build_runner but we're creating it manually

class MockFirebaseAuth {}
class MockFirebaseFirestore {}
class MockUser {}
class MockUserCredential {}
class MockDocumentSnapshot {}

// Export the classes to match what the annotations would generate
export 'auth_provider_test.dart';