// Mocks for auth_provider_test.dart
// This file is typically generated by build_runner but we're creating it manually

import 'package:mockito/mockito.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class MockFirebaseAuth extends Mock implements FirebaseAuth {}
class MockFirebaseFirestore extends Mock implements FirebaseFirestore {}
class MockUser extends Mock implements User {}
class MockUserCredential extends Mock implements UserCredential {}
class MockDocumentSnapshot extends Mock implements DocumentSnapshot {}

// Export the classes to match what the annotations would generate
export 'auth_provider_test.dart';