// Mocks for member_provider_test.dart
// This file is typically generated by build_runner but we're creating it manually

class MockFirebaseFirestore {}
class MockCollectionReference {}
class MockQuery {}
class MockQuerySnapshot {}
class MockDocumentSnapshot {}

// Export the classes to match what the annotations would generate
export 'member_provider_test.dart';