// Mocks for meal_plan_flow_test.dart
// This file is typically generated by build_runner but we're creating it manually

class MockFirebaseFirestore {}
class MockCollectionReference {}
class MockDocumentReference {}
class MockDocumentSnapshot {}
class MockQuery {}
class MockQuerySnapshot {}
class MockFirebaseAuth {}
class MockUser {}

// Export the classes to match what the annotations would generate
export 'meal_plan_flow_test.dart';